// src/enums/loaiThongBao.enum.js
const LoaiThongBao = Object.freeze({
  SU_KIEN_MOI_CHO_DUYET_BGH: 'SU_KIEN_MOI_CHO_DUYET_BGH',
  SU_KIEN_DA_DUYET_BGH: 'SU_KIEN_DA_DUYET_BGH',
  SU_KIEN_BI_TU_CHOI_BGH: 'SU_KIEN_BI_TU_CHOI_BGH',
  YC_PHONG_MOI_CHO_CSVC: 'YC_PHONG_MOI_CHO_CSVC',
  YC_PHONG_DA_DUYET_CSVC: 'YC_PHONG_DA_DUYET_CSVC',
  YC_PHONG_BI_TU_CHOI_CSVC: 'YC_PHONG_BI_TU_CHOI_CSVC',
  YC_HUY_SK_MOI_CHO_BGH: 'YC_HUY_SK_MOI_CHO_BGH',
  YC_HUY_SK_DA_DUYET: 'YC_HUY_SK_DA_DUYET',
  YC_HUY_SK_BI_TU_CHOI: 'YC_HUY_SK_BI_TU_CHOI',
  PHONG_DA_GIAI_PHONG_DO_HUY_SK: 'PHONG_DA_GIAI_PHONG_DO_HUY_SK',
  SK_SAP_DIEN_RA: 'SK_SAP_DIEN_RA',
  THONG_BAO_CHUNG: 'THONG_BAO_CHUNG',
  SU_KIEN_TU_DONG_HUY_QUA_HAN: 'SU_KIEN_TU_DONG_HUY_QUA_HAN',
  SU_KIEN_NHAC_NHO_DUYET_BGH: 'SU_KIEN_NHAC_NHO_DUYET_BGH',
  YC_PHONG_NHAC_NHO_DUYET_CSVC: 'YC_PHONG_NHAC_NHO_DUYET_CSVC',
  BGH_YEU_CAU_CHINH_SUA_SK: 'BGH_YEU_CAU_CHINH_SUA_SK',
  CSVC_YEU_CAU_CHINH_SUA_YCPCT: 'CSVC_YEU_CAU_CHINH_SUA_YCPCT',
  YC_DOI_PHONG_MOI_CHO_CSVC: 'YC_DOI_PHONG_MOI_CHO_CSVC',
  YC_DOI_PHONG_DA_DUYET: 'YC_DOI_PHONG_DA_DUYET',
  YC_DOI_PHONG_BI_TU_CHOI: 'YC_DOI_PHONG_BI_TU_CHOI',
  SU_KIEN_DA_CHINH_SUA_CHO_BGH: 'SU_KIEN_DA_CHINH_SUA_CHO_BGH',
  THONG_BAO_CONG_KHAI: 'THONG_BAO_CONG_KHAI',
});

export default LoaiThongBao;
