// src/enums/maTrangThaiSK.enum.js
const MaTrangThaiSK = Object.freeze({
  CHO_DUYET_BGH: 'CHO_DUYET_BGH',
  BGH_YEU_CAU_CHINH_SUA_SK: 'BGH_YEU_CAU_CHINH_SUA_SK',
  DA_DUYET_BGH: 'DA_DUYET_BGH',
  BI_TU_CHOI_BGH: 'BI_TU_CHOI_BGH',
  DA_HUY_BOI_NGUOI_TAO: 'DA_HUY_BOI_NGUOI_TAO',
  CHO_DUYET_PHONG: 'CHO_DUYET_PHONG',
  DA_XAC_NHAN_PHONG: 'DA_XAC_NHAN_PHONG',
  PHONG_BI_TU_CHOI: 'PHONG_BI_TU_CHOI',
  CHO_DUYET_HUY_SAU_DUYET: 'CHO_DUYET_HUY_SAU_DUYET',
  DA_HUY: 'DA_HUY',
  HOAN_THANH: 'HOAN_THANH',
  HUY_DO_QUA_HAN_XU_LY: 'HUY_DO_QUA_HAN_XU_LY',
});

export default MaTrangThaiSK;
