// src/enums/maTrangThaiYeuCauPhong.enum.js
const MaTrangThaiYeuCauPhong = Object.freeze({
  YCCP_CHO_XU_LY: 'YCCP_CHO_XU_LY',
  YCCP_DANG_XU_LY: 'YCCP_DANG_XU_LY',
  YCCP_DA_XU_LY_MOT_PHAN: 'YCCP_DA_XU_LY_MOT_PHAN',
  YCCP_HOAN_TAT_DUYET: 'YCCP_HOAN_TAT_DUYET',
  YCCP_TU_CHOI_TOAN_BO: 'YCCP_TU_CHOI_TOAN_BO',
  YCCP_DA_HUY_BOI_NGUOI_TAO: 'YCCP_DA_HUY_BOI_NGUOI_TAO',
  YCCP_TU_DONG_HUY: 'YCCP_TU_DONG_HUY',
  YCCPCT_CHO_DUYET: 'YCCPCT_CHO_DUYET',
  CSVC_YEU_CAU_CHINH_SUA_CT: 'CSVC_YEU_CAU_CHINH_SUA_CT',
  YCCPCT_DA_XEP_PHONG: 'YCCPCT_DA_XEP_PHONG',
  YCCPCT_KHONG_PHU_HOP: 'YCCPCT_KHONG_PHU_HOP',
  YCCPCT_DA_HUY: 'YCCPCT_DA_HUY',
});

export default MaTrangThaiYeuCauPhong;
